import type {
  User,
  Role,
  Zone,
  TelcoOperator,
  OperatorService,
  Currency,
  Agent,
  Dealer,
  Transaction,
  TransactionApproval,
  DashboardStats,
} from '../types';

// Mock Currencies
export const mockCurrencies: Currency[] = [
  { id: '1', code: 'SSP', name: 'South Sudanese Pound', symbol: 'SSP', decimals: 2 },
  { id: '2', code: 'USD', name: 'US Dollar', symbol: '$', decimals: 2 },
];

// Mock Zones
export const mockZones: Zone[] = [
  { id: '1', code: 'JUB', name: 'Juba', createdAt: new Date('2024-01-01') },
  { id: '2', code: 'WAU', name: 'Wau', createdAt: new Date('2024-01-01') },
  { id: '3', code: 'MAL', name: 'Malakal', createdAt: new Date('2024-01-01') },
  { id: '4', code: 'BOR', name: 'Bor', createdAt: new Date('2024-01-01') },
  { id: '5', code: 'YEI', name: 'Yei', createdAt: new Date('2024-01-01') },
];

// Mock Telco Operators
export const mockOperators: TelcoOperator[] = [
  {
    id: '1',
    code: 'MTN',
    name: 'MTN South Sudan',
    contractReference: 'MTN-SS-2024-001',
    commissionAccount: '1000-MTN-COMM',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'ZAIN',
    name: 'Zain South Sudan',
    contractReference: 'ZAIN-SS-2024-001',
    commissionAccount: '1000-ZAIN-COMM',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'DIGITEL',
    name: 'Digitel South Sudan',
    contractReference: 'DIG-SS-2024-001',
    commissionAccount: '1000-DIG-COMM',
    createdAt: new Date('2024-01-01'),
  },
];

// Mock Operator Services
export const mockOperatorServices: OperatorService[] = [
  {
    id: '1',
    operatorId: '1',
    serviceType: 'AIRTIME',
    serviceAccount: 'MTN-AIRTIME-001',
    code: 'MTN-AIR',
    displayName: 'MTN Airtime',
    isEnabled: true,
  },
  {
    id: '2',
    operatorId: '1',
    serviceType: 'MOBILE_MONEY',
    serviceAccount: 'MTN-MM-001',
    code: 'MTN-MM',
    displayName: 'MTN Mobile Money',
    isEnabled: true,
  },
  {
    id: '3',
    operatorId: '1',
    serviceType: 'SIM_CARD',
    serviceAccount: 'MTN-SIM-001',
    code: 'MTN-SIM',
    displayName: 'MTN SIM Cards',
    isEnabled: true,
  },
  {
    id: '4',
    operatorId: '2',
    serviceType: 'AIRTIME',
    serviceAccount: 'ZAIN-AIRTIME-001',
    code: 'ZAIN-AIR',
    displayName: 'Zain Airtime',
    isEnabled: true,
  },
  {
    id: '5',
    operatorId: '2',
    serviceType: 'MOBILE_MONEY',
    serviceAccount: 'ZAIN-MM-001',
    code: 'ZAIN-MM',
    displayName: 'Zain Mobile Money',
    isEnabled: true,
  },
  {
    id: '6',
    operatorId: '3',
    serviceType: 'AIRTIME',
    serviceAccount: 'DIG-AIRTIME-001',
    code: 'DIG-AIR',
    displayName: 'Digitel Airtime',
    isEnabled: true,
  },
];

// Mock Roles (must be before Users)
export const mockRoles: Role[] = [
  {
    id: '1',
    name: 'ADMIN',
    description: 'Administrateur système avec tous les privilèges',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'CASH_OFFICER',
    description: 'Agent de collecte - Niveau 1 d\'approbation',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'CFO',
    description: 'Directeur Financier - Niveau 2 d\'approbation',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'OPERATIONS_MANAGER',
    description: 'Responsable Opérations - Niveau 2 d\'approbation',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'AUDITOR',
    description: 'Auditeur - Consultation uniquement',
    createdAt: new Date('2024-01-01'),
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    uuid: 'uuid-admin-001',
    phone: '+211912345678',
    username: 'admin',
    displayName: 'System Administrator',
    email: 'admin@afrilandbank.ss',
    password: 'admin123',
    country: 'South Sudan',
    countryISO: 'SS',
    connexionAttemps: 0,
    isActive: true,
    roles: [mockRoles[0]], // ADMIN
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    version: 0,
  },
  {
    id: '2',
    uuid: 'uuid-officer-001',
    phone: '+211912345679',
    username: 'officer1',
    displayName: 'John Doe',
    email: 'john.doe@afrilandbank.ss',
    password: 'officer123',
    country: 'South Sudan',
    countryISO: 'SS',
    connexionAttemps: 0,
    isActive: true,
    roles: [mockRoles[1]], // CASH_OFFICER
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    version: 0,
  },
  {
    id: '3',
    uuid: 'uuid-cfo-001',
    phone: '+211912345680',
    username: 'cfo',
    displayName: 'Jane Smith',
    email: 'jane.smith@afrilandbank.ss',
    password: 'cfo123',
    country: 'South Sudan',
    countryISO: 'SS',
    connexionAttemps: 0,
    isActive: true,
    roles: [mockRoles[2]], // CFO
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    version: 0,
  },
];

// Mock Agents
export const mockAgents: Agent[] = [
  {
    id: '1',
    code: 'AGT-WAU-001',
    name: 'Peter Garang',
    zoneId: '2',
    status: 'ACTIVE',
    accountNumber: '2001-AGT-001',
    contractReference: 'AGT-WAU-2024-001',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    code: 'AGT-MAL-001',
    name: 'Mary Nyandeng',
    zoneId: '3',
    status: 'ACTIVE',
    accountNumber: '2001-AGT-002',
    contractReference: 'AGT-MAL-2024-001',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    code: 'AGT-BOR-001',
    name: 'David Machar',
    zoneId: '4',
    status: 'ACTIVE',
    accountNumber: '2001-AGT-003',
    contractReference: 'AGT-BOR-2024-001',
    createdAt: new Date('2024-02-01'),
  },
];

// Mock Dealers
export const mockDealers: Dealer[] = [
  {
    id: '1',
    type: 'DISTRIBUTOR',
    name: 'Top Dealers Ltd',
    zoneId: '1',
    accountNumber: '3001-DEALER-001',
    kycStatus: 'VERIFIED',
    contractReference: 'DEALER-JUB-2024-001',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '2',
    type: 'RESELLER',
    name: 'Wau Communications',
    zoneId: '2',
    accountNumber: '3001-DEALER-002',
    kycStatus: 'VERIFIED',
    contractReference: 'DEALER-WAU-2024-001',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    type: 'DISTRIBUTOR',
    name: 'Malakal Telecom Services',
    zoneId: '3',
    accountNumber: '3001-DEALER-003',
    kycStatus: 'VERIFIED',
    contractReference: 'DEALER-MAL-2024-001',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '4',
    type: 'RESELLER',
    name: 'Bor Mobile Shop',
    zoneId: '4',
    accountNumber: '3001-DEALER-004',
    kycStatus: 'PENDING',
    contractReference: 'DEALER-BOR-2024-001',
    createdAt: new Date('2024-02-01'),
  },
];

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: '1',
    reference: 'TRX-2025-10-04-0001',
    createdAt: new Date('2025-10-04T10:30:00'),
    createdByUserId: '1',
    agentId: '1',
    dealerId: '2',
    operatorId: '1',
    operatorServiceId: '1',
    serviceType: 'AIRTIME',
    amount: 50000,
    currencyId: '1',
    phoneNumber: '+211922334455',
    sourceOfFunds: 'Cash deposit from dealer',
    depositorName: 'James Bol',
    status: 'PENDING',
    version: 0,
  },
  {
    id: '2',
    reference: 'TRX-2025-10-04-0002',
    createdAt: new Date('2025-10-04T11:15:00'),
    createdByUserId: '2',
    agentId: '2',
    dealerId: '3',
    operatorId: '2',
    operatorServiceId: '5',
    serviceType: 'MOBILE_MONEY',
    amount: 100000,
    currencyId: '1',
    phoneNumber: '+211933445566',
    sourceOfFunds: 'Business revenue',
    depositorName: 'Sarah Akech',
    status: 'VALIDATED',
    version: 0,
  },
  {
    id: '3',
    reference: 'TRX-2025-10-03-0015',
    createdAt: new Date('2025-10-03T14:20:00'),
    createdByUserId: '2',
    dealerId: '1',
    operatorId: '1',
    operatorServiceId: '2',
    serviceType: 'MOBILE_MONEY',
    amount: 250000,
    currencyId: '1',
    phoneNumber: '+211944556677',
    sourceOfFunds: 'Cash collection',
    depositorName: 'Michael Deng',
    status: 'APPROVED',
    approvedAt: new Date('2025-10-03T15:00:00'),
    version: 0,
  },
  {
    id: '4',
    reference: 'TRX-2025-10-02-0032',
    createdAt: new Date('2025-10-02T09:45:00'),
    createdByUserId: '1',
    agentId: '3',
    dealerId: '4',
    operatorId: '3',
    operatorServiceId: '6',
    serviceType: 'AIRTIME',
    amount: 75000,
    currencyId: '1',
    phoneNumber: '+211955667788',
    sourceOfFunds: 'Dealer payment',
    depositorName: 'Rebecca Aluel',
    status: 'COMPLETED',
    approvedAt: new Date('2025-10-02T10:30:00'),
    completedAt: new Date('2025-10-02T10:45:00'),
    version: 0,
  },
  {
    id: '5',
    reference: 'TRX-2025-10-01-0021',
    createdAt: new Date('2025-10-01T16:00:00'),
    createdByUserId: '2',
    agentId: '1',
    dealerId: '2',
    operatorId: '2',
    operatorServiceId: '4',
    serviceType: 'AIRTIME',
    amount: 30000,
    currencyId: '1',
    phoneNumber: '+211966778899',
    sourceOfFunds: 'Daily collection',
    depositorName: 'Thomas Majok',
    status: 'REJECTED',
    statusReason: 'Invalid documentation',
    rejectedAt: new Date('2025-10-01T16:30:00'),
    version: 0,
  },
];

// Mock Transaction Approvals
export const mockTransactionApprovals: TransactionApproval[] = [
  {
    id: '1',
    transactionId: '2',
    approverUserId: '2',
    approverRole: 'OFFICER',
    level: 1,
    action: 'APPROVE',
    comment: 'Documentation verified',
    createdAt: new Date('2025-10-04T11:30:00'),
  },
  {
    id: '2',
    transactionId: '3',
    approverUserId: '2',
    approverRole: 'OFFICER',
    level: 1,
    action: 'APPROVE',
    createdAt: new Date('2025-10-03T14:45:00'),
  },
  {
    id: '3',
    transactionId: '3',
    approverUserId: '3',
    approverRole: 'CFO',
    level: 2,
    action: 'APPROVE',
    comment: 'Final approval granted',
    createdAt: new Date('2025-10-03T15:00:00'),
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalTransactions: 156,
  pendingTransactions: 12,
  approvedTransactions: 98,
  rejectedTransactions: 8,
  totalAmount: 12450000,
  activeAgents: 15,
  activeDealers: 42,
  recentTransactions: mockTransactions.slice(0, 5),
};
